spring.application.name=${APPLICATION_NAME}

# ===========================
# Server
# ===========================
server.port=${SERVER_PORT}

# ===========================
# MongoDB
# ===========================
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE}
spring.mongodb.auto-index-creation=${AUTO_INDEX_CREATION}


# ===========================
# OAuth2 / Keycloak (Resource Server)
# ===========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}

# ===========================
# Keycloak Admin (for creating users via API)
# ===========================
keycloak.admin.server-url=${KEYCLOAK_SERVER_URL}
keycloak.admin.realm=${KEYCLOAK_REALM}
keycloak.admin.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.admin.client-secret=${KEYCLOAK_CLIENT_SECRET}


# ===========================
# DevTools
# ===========================
spring.devtools.restart.enabled=${SPRING_DEVTOOLS_RESTART_ENABLED}
spring.devtools.livereload.enabled=${SPRING_DEVTOOLS_LIVERELOAD_ENABLED}

# ===========================
# Logging
# ===========================
logging.level.org.springframework.security=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY}
logging.level.org.springframework.data.mongodb=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB}
logging.level.org.keycloak=${LOGGING_LEVEL_ORG_KEYCLOAK}
logging.level.org.apache.http=${LOGGING_LEVEL_ORG_APACHE_HTTP}
spring.data.mongodb.auto-index-creation=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION}
