spring.application.name=Inventory

# ===========================
# Server
# ===========================
server.port=8081

# ===========================
# MongoDB
# ===========================
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

# ===========================
# OAuth2 / Keycloak (Resource Server)
# ===========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}

# ===========================
# Keycloak Admin (for creating users via API)
# ===========================
keycloak.admin.server-url=${KEYCLOAK_SERVER_URL}
keycloak.admin.realm=${KEYCLOAK_REALM}
keycloak.admin.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.admin.client-secret=${KEYCLOAK_CLIENT_SECRET}


# ===========================
# DevTools
# ===========================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# ===========================
# Logging
# ===========================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.keycloak=DEBUG
logging.level.org.apache.http=DEBUG